web:
  build: .
  command: bin/web
  environment:
    - RACK_ENV=development
  ports:
    - 80:3000
    - 443:3000
  volumes:
    - .:/app
  links:
    - postgres
    - redis
worker:
  build: .
  command: bin/worker
  environment:
    - RACK_ENV=development
  volumes:
    - .:/app
  links:
    - postgres
    - redis
redis:
  image: convox/redis
  ports:
    - 6379
postgres:
  image: convox/postgres
  ports:
    - 5432
