web:
  build: .
  command: bin/web
  environment:
    - RACK_ENV=development
    - POSTGRES_URL=postgres://postgres:password@postgres:5432/app
    - REDIS_URL=redis://redis:password@redis:6379/0
  ports:
    - 80:3000
    - 443:3000
  volumes:
    - .:/app
  links:
    - postgres
    - redis
worker:
  build: .
  command: bin/worker
  environment:
    - RACK_ENV=development
    - POSTGRES_URL=postgres://postgres:password@postgres:5432/app
    - REDIS_URL=redis://redis:password@redis:6379/0
  volumes:
    - .:/app
  links:
    - postgres
    - redis
redis:
  image: convox/redis
postgres:
  image: convox/postgres
